apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  type: NodePort  # or use LoadBalancer if on cloud (EKS, GKE, etc.)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # optional; if omitted, Kubernetes assigns one
